2025-02-23T16:23:22.5893643Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-02-23T16:23:22.5894955Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-02-23T16:23:22.5949811Z shell: /usr/bin/bash -l {0}
2025-02-23T16:23:22.5950092Z env:
2025-02-23T16:23:22.5950327Z   CACHE_NUMBER: 0
2025-02-23T16:23:22.5950961Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-23T16:23:22.5951634Z   CODECOV_TOKEN: 
2025-02-23T16:23:22.5951875Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-23T16:23:22.5952194Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-23T16:23:22.5952568Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-23T16:23:22.5952933Z ##[endgroup]
2025-02-23T16:23:32.4409241Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:32.4409661Z 
2025-02-23T16:23:32.4409829Z invalid escape sequence '\s'
2025-02-23T16:23:32.4410123Z 
2025-02-23T16:23:32.4431862Z /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:23:32.4432540Z 
2025-02-23T16:23:32.4432721Z invalid escape sequence '\s'
2025-02-23T16:23:32.4433013Z 
2025-02-23T16:23:32.4787540Z /home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:23:32.4788775Z 
2025-02-23T16:23:32.4789058Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:23:32.4789484Z 
2025-02-23T16:23:34.3831552Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:34.3831940Z 
2025-02-23T16:23:34.3832108Z invalid escape sequence '\s'
2025-02-23T16:23:34.3832382Z 
2025-02-23T16:23:36.8476157Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:36.8476471Z 
2025-02-23T16:23:36.8476596Z invalid escape sequence '\s'
2025-02-23T16:23:36.8476841Z 
2025-02-23T16:23:37.6966330Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:37.6966737Z 
2025-02-23T16:23:37.6966914Z invalid escape sequence '\s'
2025-02-23T16:23:37.6967220Z 
2025-02-23T16:23:37.6989084Z /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:23:37.6989760Z 
2025-02-23T16:23:37.6990002Z invalid escape sequence '\s'
2025-02-23T16:23:37.6990293Z 
2025-02-23T16:23:37.7430495Z /home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:23:37.7431343Z 
2025-02-23T16:23:37.7431620Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:23:37.7432045Z 
2025-02-23T16:23:39.2653465Z ============================= test session starts ==============================
2025-02-23T16:23:39.2654248Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-23T16:23:39.2654827Z rootdir: /home/runner/work/tardis/tardis
2025-02-23T16:23:39.2655561Z configfile: pyproject.toml
2025-02-23T16:23:39.2656158Z plugins: metadata-3.1.1, anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1
2025-02-23T16:23:39.2656882Z collected 1795 items / 1 error / 2 deselected / 1793 selected
2025-02-23T16:23:39.2657283Z 
2025-02-23T16:23:39.2657454Z ==================================== ERRORS ====================================
2025-02-23T16:23:39.2657998Z _____ ERROR collecting tardis/io/model/readers/tests/test_artis_readers.py _____
2025-02-23T16:23:39.2658780Z tardis/io/model/readers/tests/test_artis_readers.py:12: in <module>
2025-02-23T16:23:39.2659457Z     @pytest.fixture
2025-02-23T16:23:39.2659871Z E   NameError: name 'pytest' is not defined
2025-02-23T16:23:39.2660433Z ------------------------------- Captured stdout --------------------------------
2025-02-23T16:23:39.2661279Z [[1mpy.warnings         [0m][[1;33mWARNING[0m]  
2025-02-23T16:23:39.2662234Z 	/home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: PytestAssertRewriteWarning:
2025-02-23T16:23:39.2663330Z 
2025-02-23T16:23:39.2663557Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:23:39.2663901Z 
2025-02-23T16:23:39.2664104Z  ([1mwarnings.py[0m:112)
2025-02-23T16:23:39.2664505Z =============================== warnings summary ===============================
2025-02-23T16:23:39.2665008Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:23:39.2665687Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:23:39.2666521Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-23T16:23:39.2667262Z   
2025-02-23T16:23:39.2669213Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-23T16:23:39.2671296Z 
2025-02-23T16:23:39.2671685Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-23T16:23:39.2672733Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-23T16:23:39.2673543Z   
2025-02-23T16:23:39.2673918Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-23T16:23:39.2674527Z   given by the platformdirs library.  To remove this warning and
2025-02-23T16:23:39.2675542Z   see the appropriate new directories, set the environment variable
2025-02-23T16:23:39.2676186Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-23T16:23:39.2676799Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-23T16:23:39.2677199Z 
2025-02-23T16:23:39.2677349Z tardis/io/model/readers/artis.py:143
2025-02-23T16:23:39.2678027Z   /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:23:39.2678693Z   
2025-02-23T16:23:39.2678977Z   invalid escape sequence '\s'
2025-02-23T16:23:39.2679226Z 
2025-02-23T16:23:39.2679538Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-23T16:23:39.2679970Z 
2025-02-23T16:23:39.2680237Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-23T16:23:39.2680819Z Coverage HTML written to dir coverage_html_report
2025-02-23T16:23:39.2681302Z Coverage XML written to file coverage.xml
2025-02-23T16:23:39.2681591Z 
2025-02-23T16:23:39.2681785Z =========================== short test summary info ============================
2025-02-23T16:23:39.2682541Z ERROR tardis/io/model/readers/tests/test_artis_readers.py - NameError: name 'pytest' is not defined
2025-02-23T16:23:39.2683358Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-23T16:23:39.2683964Z ================== 2 deselected, 4 warnings, 1 error in 9.03s ==================
2025-02-23T16:23:39.9024152Z ##[error]Process completed with exit code 2.
