2025-02-23T16:24:10.9129260Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-02-23T16:24:10.9130470Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-02-23T16:24:10.9213140Z shell: /bin/bash -l {0}
2025-02-23T16:24:10.9213610Z env:
2025-02-23T16:24:10.9213860Z   CACHE_NUMBER: 0
2025-02-23T16:24:10.9214530Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-23T16:24:10.9227450Z   CODECOV_TOKEN: 
2025-02-23T16:24:10.9227670Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-02-23T16:24:10.9227950Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-02-23T16:24:10.9228310Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-02-23T16:24:10.9228670Z ##[endgroup]
2025-02-23T16:24:23.8318890Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:23.8418380Z 
2025-02-23T16:24:23.8448010Z invalid escape sequence '\s'
2025-02-23T16:24:23.8448530Z 
2025-02-23T16:24:23.8449060Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:23.8449790Z 
2025-02-23T16:24:23.8450000Z invalid escape sequence '\s'
2025-02-23T16:24:23.8450220Z 
2025-02-23T16:24:23.8573160Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:24:23.8573670Z 
2025-02-23T16:24:23.8573860Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:23.8574120Z 
2025-02-23T16:24:25.4039520Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:25.4039910Z 
2025-02-23T16:24:25.4040090Z invalid escape sequence '\s'
2025-02-23T16:24:25.4040220Z 
2025-02-23T16:24:27.3023410Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:27.3023830Z 
2025-02-23T16:24:27.3023900Z invalid escape sequence '\s'
2025-02-23T16:24:27.3024290Z 
2025-02-23T16:24:28.3811930Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:28.3911490Z 
2025-02-23T16:24:28.3966210Z invalid escape sequence '\s'
2025-02-23T16:24:28.3966560Z 
2025-02-23T16:24:28.3967060Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:28.3967590Z 
2025-02-23T16:24:28.3967820Z invalid escape sequence '\s'
2025-02-23T16:24:28.3968350Z 
2025-02-23T16:24:28.4373740Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:24:28.4473300Z 
2025-02-23T16:24:28.4574550Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:28.4675470Z 
2025-02-23T16:24:30.2054260Z ============================= test session starts ==============================
2025-02-23T16:24:30.2055030Z platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-23T16:24:30.2055440Z rootdir: /Users/runner/work/tardis/tardis
2025-02-23T16:24:30.2055810Z configfile: pyproject.toml
2025-02-23T16:24:30.2056240Z plugins: cov-5.0.0, html-4.1.1, metadata-3.1.1, doctestplus-1.2.1, anyio-4.4.0
2025-02-23T16:24:30.2056690Z collected 1795 items / 1 error / 2 deselected / 1793 selected
2025-02-23T16:24:30.2056950Z 
2025-02-23T16:24:30.2057130Z ==================================== ERRORS ====================================
2025-02-23T16:24:30.2057560Z _____ ERROR collecting tardis/io/model/readers/tests/test_artis_readers.py _____
2025-02-23T16:24:30.2058180Z tardis/io/model/readers/tests/test_artis_readers.py:12: in <module>
2025-02-23T16:24:30.2058590Z     @pytest.fixture
2025-02-23T16:24:30.2058940Z E   NameError: name 'pytest' is not defined
2025-02-23T16:24:30.2059350Z ------------------------------- Captured stdout --------------------------------
2025-02-23T16:24:30.2060910Z [[1mpy.warnings         [0m][[1;33mWARNING[0m]  
2025-02-23T16:24:30.2061620Z 	/Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: PytestAssertRewriteWarning:
2025-02-23T16:24:30.2063740Z 
2025-02-23T16:24:30.2065640Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:30.2066480Z 
2025-02-23T16:24:30.2066830Z  ([1mwarnings.py[0m:112)
2025-02-23T16:24:30.2067320Z =============================== warnings summary ===============================
2025-02-23T16:24:30.2068210Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:30.2068710Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:30.2069270Z   /Users/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-23T16:24:30.2069960Z   
2025-02-23T16:24:30.2071110Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-23T16:24:30.2072320Z 
2025-02-23T16:24:30.2072670Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-23T16:24:30.2073570Z   /Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-23T16:24:30.2074200Z   
2025-02-23T16:24:30.2074640Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-23T16:24:30.2075180Z   given by the platformdirs library.  To remove this warning and
2025-02-23T16:24:30.2075780Z   see the appropriate new directories, set the environment variable
2025-02-23T16:24:30.2076250Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-23T16:24:30.2076740Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-23T16:24:30.2077080Z 
2025-02-23T16:24:30.2077180Z tardis/io/model/readers/artis.py:143
2025-02-23T16:24:30.2077830Z   /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:30.2078320Z   
2025-02-23T16:24:30.2078640Z   invalid escape sequence '\s'
2025-02-23T16:24:30.2078930Z 
2025-02-23T16:24:30.2079140Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-23T16:24:30.2079460Z 
2025-02-23T16:24:30.2079700Z ---------- coverage: platform darwin, python 3.12.4-final-0 ----------
2025-02-23T16:24:30.2080180Z Coverage HTML written to dir coverage_html_report
2025-02-23T16:24:30.2080510Z Coverage XML written to file coverage.xml
2025-02-23T16:24:30.2080770Z 
2025-02-23T16:24:30.2080990Z =========================== short test summary info ============================
2025-02-23T16:24:30.2081530Z ERROR tardis/io/model/readers/tests/test_artis_readers.py - NameError: name 'pytest' is not defined
2025-02-23T16:24:30.2082150Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-23T16:24:30.2082640Z ================== 2 deselected, 4 warnings, 1 error in 8.22s ==================
2025-02-23T16:24:30.8643760Z ##[error]Process completed with exit code 2.
