2025-02-25T03:22:51.1869683Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-02-25T03:22:51.1871540Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-02-25T03:22:51.1926463Z shell: /usr/bin/bash -l {0}
2025-02-25T03:22:51.1926906Z env:
2025-02-25T03:22:51.1927089Z   CACHE_NUMBER: 0
2025-02-25T03:22:51.1927709Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-25T03:22:51.1928361Z   CODECOV_TOKEN: 
2025-02-25T03:22:51.1928585Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-25T03:22:51.1928903Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-25T03:22:51.1929267Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-25T03:22:51.1929627Z ##[endgroup]
2025-02-25T03:23:09.0051698Z ============================= test session starts ==============================
2025-02-25T03:23:09.0052282Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-25T03:23:09.0052724Z rootdir: /home/runner/work/tardis/tardis
2025-02-25T03:23:09.0053078Z configfile: pyproject.toml
2025-02-25T03:23:09.0053514Z plugins: metadata-3.1.1, anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1
2025-02-25T03:23:09.0054077Z collected 1787 items / 1 error / 2 deselected / 1785 selected
2025-02-25T03:23:09.0054364Z 
2025-02-25T03:23:09.0054501Z ==================================== ERRORS ====================================
2025-02-25T03:23:09.0054996Z __ ERROR collecting tardis/energy_input/tests/test_gamma_ray_packet_source.py __
2025-02-25T03:23:09.0055854Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/energy_input/tests/test_gamma_ray_packet_source.py'.
2025-02-25T03:23:09.0056653Z Hint: make sure your test modules/packages have valid Python names.
2025-02-25T03:23:09.0057070Z Traceback:
2025-02-25T03:23:09.0057495Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-25T03:23:09.0058070Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-25T03:23:09.0058602Z tardis/energy_input/tests/test_gamma_ray_packet_source.py:4: in <module>
2025-02-25T03:23:09.0059213Z     from tardis.energy_input.gamma_ray_packet_source import RadioactivePacketSource
2025-02-25T03:23:09.0060323Z E   ImportError: cannot import name 'RadioactivePacketSource' from 'tardis.energy_input.gamma_ray_packet_source' (/home/runner/work/tardis/tardis/tardis/energy_input/gamma_ray_packet_source.py)
2025-02-25T03:23:09.0061260Z =============================== warnings summary ===============================
2025-02-25T03:23:09.0061582Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:09.0061887Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:09.0062381Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-25T03:23:09.0062853Z   
2025-02-25T03:23:09.0064073Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-25T03:23:09.0065293Z 
2025-02-25T03:23:09.0065542Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-25T03:23:09.0066222Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-25T03:23:09.0066730Z   
2025-02-25T03:23:09.0066977Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-25T03:23:09.0067363Z   given by the platformdirs library.  To remove this warning and
2025-02-25T03:23:09.0068045Z   see the appropriate new directories, set the environment variable
2025-02-25T03:23:09.0068442Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-25T03:23:09.0068824Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-25T03:23:09.0069077Z 
2025-02-25T03:23:09.0069185Z tardis/plasma/properties/__init__.py:17
2025-02-25T03:23:09.0069787Z   /home/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-25T03:23:09.0070219Z   
2025-02-25T03:23:09.0070877Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-25T03:23:09.0071624Z 
2025-02-25T03:23:09.0071823Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-25T03:23:09.0072111Z 
2025-02-25T03:23:09.0072276Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-25T03:23:09.0072648Z Coverage HTML written to dir coverage_html_report
2025-02-25T03:23:09.0072951Z Coverage XML written to file coverage.xml
2025-02-25T03:23:09.0073136Z 
2025-02-25T03:23:09.0073261Z =========================== short test summary info ============================
2025-02-25T03:23:09.0073642Z ERROR tardis/energy_input/tests/test_gamma_ray_packet_source.py
2025-02-25T03:23:09.0074042Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-25T03:23:09.0074415Z ================== 2 deselected, 4 warnings, 1 error in 9.04s ==================
2025-02-25T03:23:09.6758169Z ##[error]Process completed with exit code 2.
