2025-01-20T13:42:30.7421820Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-01-20T13:42:30.7423324Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-01-20T13:42:30.7450456Z shell: /usr/bin/bash -l {0}
2025-01-20T13:42:30.7450695Z env:
2025-01-20T13:42:30.7450860Z   CACHE_NUMBER: 0
2025-01-20T13:42:30.7451465Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-01-20T13:42:30.7452106Z   CODECOV_TOKEN: 
2025-01-20T13:42:30.7452321Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-01-20T13:42:30.7452613Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-01-20T13:42:30.7452955Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-01-20T13:42:30.7453288Z ##[endgroup]
2025-01-20T13:42:47.4896810Z ============================= test session starts ==============================
2025-01-20T13:42:47.4897821Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-01-20T13:42:47.4898577Z rootdir: /home/runner/work/tardis/tardis
2025-01-20T13:42:47.4899179Z configfile: pyproject.toml
2025-01-20T13:42:47.4899920Z plugins: anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1, metadata-3.1.1
2025-01-20T13:42:47.4900877Z collected 1768 items / 1 error / 2 deselected / 1766 selected
2025-01-20T13:42:47.4901375Z 
2025-01-20T13:42:47.4901533Z ==================================== ERRORS ====================================
2025-01-20T13:42:47.4902096Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-01-20T13:42:47.4902934Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-01-20T13:42:47.4903542Z Hint: make sure your test modules/packages have valid Python names.
2025-01-20T13:42:47.4903868Z Traceback:
2025-01-20T13:42:47.4904209Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-01-20T13:42:47.4904680Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-01-20T13:42:47.4905036Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-01-20T13:42:47.4905368Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-01-20T13:42:47.4905669Z tardis/io/logger/logger.py:5: in <module>
2025-01-20T13:42:47.4905924Z     import panel as pn
2025-01-20T13:42:47.4906392Z E   ModuleNotFoundError: No module named 'panel'
2025-01-20T13:42:47.4906721Z =============================== warnings summary ===============================
2025-01-20T13:42:47.4907036Z tardis/io/configuration/config_validator.py:6
2025-01-20T13:42:47.4907326Z tardis/io/configuration/config_validator.py:6
2025-01-20T13:42:47.4907811Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-01-20T13:42:47.4908276Z   
2025-01-20T13:42:47.4909487Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-01-20T13:42:47.4910685Z 
2025-01-20T13:42:47.4910924Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-01-20T13:42:47.4911597Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-01-20T13:42:47.4912096Z   
2025-01-20T13:42:47.4912339Z   Jupyter is migrating its paths to use standard platformdirs
2025-01-20T13:42:47.4912724Z   given by the platformdirs library.  To remove this warning and
2025-01-20T13:42:47.4913109Z   see the appropriate new directories, set the environment variable
2025-01-20T13:42:47.4913915Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-01-20T13:42:47.4914476Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-01-20T13:42:47.4914712Z 
2025-01-20T13:42:47.4914859Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-01-20T13:42:47.4915457Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-01-20T13:42:47.4915979Z   
2025-01-20T13:42:47.4916819Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:42:47.4917384Z 
2025-01-20T13:42:47.4917528Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-01-20T13:42:47.4918120Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-01-20T13:42:47.4918640Z   
2025-01-20T13:42:47.4919189Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:42:47.4919740Z 
2025-01-20T13:42:47.4919877Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-01-20T13:42:47.4920457Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-01-20T13:42:47.4920970Z   
2025-01-20T13:42:47.4921507Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:42:47.4922042Z 
2025-01-20T13:42:47.4922225Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-01-20T13:42:47.4922485Z 
2025-01-20T13:42:47.4922658Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-01-20T13:42:47.4923009Z Coverage HTML written to dir coverage_html_report
2025-01-20T13:42:47.4923303Z Coverage XML written to file coverage.xml
2025-01-20T13:42:47.4923476Z 
2025-01-20T13:42:47.4923603Z =========================== short test summary info ============================
2025-01-20T13:42:47.4923911Z ERROR tardis/io/logger/tests/test_logging.py
2025-01-20T13:42:47.4924224Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-01-20T13:42:47.4924584Z ================== 2 deselected, 6 warnings, 1 error in 9.03s ==================
2025-01-20T13:42:48.1420621Z ##[error]Process completed with exit code 2.
