2025-02-25T03:22:49.9366883Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-25T03:22:49.9368153Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-25T03:22:49.9423538Z shell: /usr/bin/bash -l {0}
2025-02-25T03:22:49.9423780Z env:
2025-02-25T03:22:49.9424150Z   CACHE_NUMBER: 0
2025-02-25T03:22:49.9424784Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-25T03:22:49.9425445Z   CODECOV_TOKEN: 
2025-02-25T03:22:49.9425666Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-25T03:22:49.9425978Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-25T03:22:49.9426334Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-25T03:22:49.9426678Z ##[endgroup]
2025-02-25T03:23:06.4375837Z ============================= test session starts ==============================
2025-02-25T03:23:06.4376824Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-25T03:23:06.4377331Z rootdir: /home/runner/work/tardis/tardis
2025-02-25T03:23:06.4377693Z configfile: pyproject.toml
2025-02-25T03:23:06.4378151Z plugins: metadata-3.1.1, anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1
2025-02-25T03:23:06.4378718Z collected 1787 items / 1 error / 1785 deselected / 2 selected
2025-02-25T03:23:06.4379113Z 
2025-02-25T03:23:06.4379339Z ==================================== ERRORS ====================================
2025-02-25T03:23:06.4380442Z __ ERROR collecting tardis/energy_input/tests/test_gamma_ray_packet_source.py __
2025-02-25T03:23:06.4381443Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/energy_input/tests/test_gamma_ray_packet_source.py'.
2025-02-25T03:23:06.4382317Z Hint: make sure your test modules/packages have valid Python names.
2025-02-25T03:23:06.4382776Z Traceback:
2025-02-25T03:23:06.4383228Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-25T03:23:06.4383855Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-25T03:23:06.4384417Z tardis/energy_input/tests/test_gamma_ray_packet_source.py:4: in <module>
2025-02-25T03:23:06.4385071Z     from tardis.energy_input.gamma_ray_packet_source import RadioactivePacketSource
2025-02-25T03:23:06.4386213Z E   ImportError: cannot import name 'RadioactivePacketSource' from 'tardis.energy_input.gamma_ray_packet_source' (/home/runner/work/tardis/tardis/tardis/energy_input/gamma_ray_packet_source.py)
2025-02-25T03:23:06.4387025Z =============================== warnings summary ===============================
2025-02-25T03:23:06.4387362Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:06.4387677Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:06.4388172Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-25T03:23:06.4388642Z   
2025-02-25T03:23:06.4390071Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-25T03:23:06.4391295Z 
2025-02-25T03:23:06.4391538Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-25T03:23:06.4392217Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-25T03:23:06.4392731Z   
2025-02-25T03:23:06.4392978Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-25T03:23:06.4393369Z   given by the platformdirs library.  To remove this warning and
2025-02-25T03:23:06.4394079Z   see the appropriate new directories, set the environment variable
2025-02-25T03:23:06.4394473Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-25T03:23:06.4394852Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-25T03:23:06.4395087Z 
2025-02-25T03:23:06.4395194Z tardis/plasma/properties/__init__.py:17
2025-02-25T03:23:06.4395652Z   /home/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-25T03:23:06.4396295Z   
2025-02-25T03:23:06.4396940Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-25T03:23:06.4397577Z 
2025-02-25T03:23:06.4397777Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-25T03:23:06.4398060Z 
2025-02-25T03:23:06.4398226Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-25T03:23:06.4398604Z Coverage HTML written to dir coverage_html_report
2025-02-25T03:23:06.4398906Z Coverage XML written to file coverage.xml
2025-02-25T03:23:06.4399082Z 
2025-02-25T03:23:06.4399210Z =========================== short test summary info ============================
2025-02-25T03:23:06.4399831Z ERROR tardis/energy_input/tests/test_gamma_ray_packet_source.py
2025-02-25T03:23:06.4400267Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-25T03:23:06.4400659Z ================ 1785 deselected, 4 warnings, 1 error in 9.41s =================
2025-02-25T03:23:07.2513329Z ##[error]Process completed with exit code 2.
