2025-02-23T16:23:47.8997669Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-23T16:23:47.8998946Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-23T16:23:47.9053613Z shell: /usr/bin/bash -l {0}
2025-02-23T16:23:47.9053852Z env:
2025-02-23T16:23:47.9054026Z   CACHE_NUMBER: 0
2025-02-23T16:23:47.9054629Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-23T16:23:47.9055260Z   CODECOV_TOKEN: 
2025-02-23T16:23:47.9055476Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-23T16:23:47.9055792Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-23T16:23:47.9056138Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-23T16:23:47.9056483Z ##[endgroup]
2025-02-23T16:23:57.8420402Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:57.8420742Z 
2025-02-23T16:23:57.8420887Z invalid escape sequence '\s'
2025-02-23T16:23:57.8421128Z 
2025-02-23T16:23:57.8442630Z /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:23:57.8443060Z 
2025-02-23T16:23:57.8443170Z invalid escape sequence '\s'
2025-02-23T16:23:57.8443343Z 
2025-02-23T16:23:57.8798885Z /home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:23:57.8799571Z 
2025-02-23T16:23:57.8799789Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:23:57.8800128Z 
2025-02-23T16:23:59.7197016Z <unknown>:143: SyntaxWarning:
2025-02-23T16:23:59.7197413Z 
2025-02-23T16:23:59.7197608Z invalid escape sequence '\s'
2025-02-23T16:23:59.7197877Z 
2025-02-23T16:24:02.3041260Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:02.3041695Z 
2025-02-23T16:24:02.3041839Z invalid escape sequence '\s'
2025-02-23T16:24:02.3042109Z 
2025-02-23T16:24:03.1628386Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:03.1628694Z 
2025-02-23T16:24:03.1628821Z invalid escape sequence '\s'
2025-02-23T16:24:03.1629030Z 
2025-02-23T16:24:03.1651636Z /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:03.1652067Z 
2025-02-23T16:24:03.1652172Z invalid escape sequence '\s'
2025-02-23T16:24:03.1652582Z 
2025-02-23T16:24:03.2113523Z /home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:24:03.2114395Z 
2025-02-23T16:24:03.2114653Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:03.2115068Z 
2025-02-23T16:24:04.7359513Z ============================= test session starts ==============================
2025-02-23T16:24:04.7360282Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-23T16:24:04.7360788Z rootdir: /home/runner/work/tardis/tardis
2025-02-23T16:24:04.7361265Z configfile: pyproject.toml
2025-02-23T16:24:04.7361862Z plugins: metadata-3.1.1, anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1
2025-02-23T16:24:04.7362837Z collected 1795 items / 1 error / 1793 deselected / 2 selected
2025-02-23T16:24:04.7363272Z 
2025-02-23T16:24:04.7363465Z ==================================== ERRORS ====================================
2025-02-23T16:24:04.7364203Z _____ ERROR collecting tardis/io/model/readers/tests/test_artis_readers.py _____
2025-02-23T16:24:04.7365031Z tardis/io/model/readers/tests/test_artis_readers.py:12: in <module>
2025-02-23T16:24:04.7365549Z     @pytest.fixture
2025-02-23T16:24:04.7365811Z E   NameError: name 'pytest' is not defined
2025-02-23T16:24:04.7366206Z ------------------------------- Captured stdout --------------------------------
2025-02-23T16:24:04.7367107Z [[1mpy.warnings         [0m][[1;33mWARNING[0m]  
2025-02-23T16:24:04.7367808Z 	/home/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: PytestAssertRewriteWarning:
2025-02-23T16:24:04.7368571Z 
2025-02-23T16:24:04.7368732Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:04.7368996Z 
2025-02-23T16:24:04.7369133Z  ([1mwarnings.py[0m:112)
2025-02-23T16:24:04.7369436Z =============================== warnings summary ===============================
2025-02-23T16:24:04.7369818Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:04.7370183Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:04.7370782Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-23T16:24:04.7371342Z   
2025-02-23T16:24:04.7373115Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-23T16:24:04.7374379Z 
2025-02-23T16:24:04.7374624Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-23T16:24:04.7375313Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-23T16:24:04.7375825Z   
2025-02-23T16:24:04.7376063Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-23T16:24:04.7376443Z   given by the platformdirs library.  To remove this warning and
2025-02-23T16:24:04.7376841Z   see the appropriate new directories, set the environment variable
2025-02-23T16:24:04.7377230Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-23T16:24:04.7377608Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-23T16:24:04.7377844Z 
2025-02-23T16:24:04.7377940Z tardis/io/model/readers/artis.py:143
2025-02-23T16:24:04.7378346Z   /home/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:04.7378745Z   
2025-02-23T16:24:04.7378920Z   invalid escape sequence '\s'
2025-02-23T16:24:04.7379066Z 
2025-02-23T16:24:04.7379263Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-23T16:24:04.7379542Z 
2025-02-23T16:24:04.7379705Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-23T16:24:04.7380061Z Coverage HTML written to dir coverage_html_report
2025-02-23T16:24:04.7380356Z Coverage XML written to file coverage.xml
2025-02-23T16:24:04.7380534Z 
2025-02-23T16:24:04.7380657Z =========================== short test summary info ============================
2025-02-23T16:24:04.7381143Z ERROR tardis/io/model/readers/tests/test_artis_readers.py - NameError: name 'pytest' is not defined
2025-02-23T16:24:04.7381653Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-23T16:24:04.7382039Z ================ 1793 deselected, 4 warnings, 1 error in 9.15s =================
2025-02-23T16:24:05.4250595Z ##[error]Process completed with exit code 2.
